services:
  ooye:
    image: ghcr.io/sim2kid/ooye-docker:latest
    container_name: ooye
    restart: unless-stopped
    ports:
      - "6693:6693"
    volumes:
      - ooye_data:/data
    # To run setup mode, uncomment the following line and run: docker-compose run ooye setup
    # command: setup

volumes:
  ooye_data:
